---
- name: Create MOTD file
  hosts: centos_remote_a
  become: true
  vars:
      text_message: " Welcome AFIP "
  tasks:
    - name: copy template file
      template:
        src: motd.j2
        dest: /etc/motd
  tags:
    - motd_config




